In [2]:
import pandas as pd

In [3]:
# Load dataset
unprocs_data = pd.read_excel("sabila.xlsx")
unprocs_data.head()

,Date/日期,时长(Duration)/秒(ss),Tag/备注,Attention/注意力,Relaxation/放松度,Delta/δ波,Theta/θ波,Low-Alpha/低α波,High-Alpha/高α波,Low-Beta/低β波,...,Pitch/俯仰角,Yaw/偏航角,Roll/滚转角,SyncRate/同步率,MentalEffort/用脑度,Familarity/熟练度,temperature/体温,heart-rate/心率,Time-set/时间集合,R-R intervals/R-R间隔
0,2024-06-23 13:10:08,471.0,Test,"1,23,61,77,100,96,75,53,34,13,11,27,37,61,66,8...","1,4,10,26,53,44,43,26,20,30,38,53,48,54,48,60,...","686419,388430,78951,531079,43097,368312,39564,...","963980,77978,24009,217083,15199,173947,124644,...","40642,9504,11341,40053,18938,4297,11504,7229,1...","6310,15413,3183,10559,9190,20287,35483,10345,4...","42227,22239,4982,23503,15573,7181,27479,11368,...",...,NaN,NaN,NaN,"0,0,0,0,0,0,0,0,0,83,74,61,58,52,52,59,71,78,8...",NaN,NaN,NaN,NaN,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1...",NaN
1,2024-06-23 12:59:06,479.0,Test,"7,8,29,56,70,83,90,93,84,83,83,90,88,91,81,75,...","26,17,41,38,35,43,48,64,77,93,94,91,96,81,75,7...","1224512,101185,92870,203956,29915,548557,5351,...","143438,56625,157187,22542,26154,61326,7730,788...","50979,4404,31693,2212,7489,8689,3985,14981,786...","15409,3341,29821,3292,16163,14455,3828,6765,20...","10988,2659,15039,6505,21814,8239,2770,22010,72...",...,NaN,NaN,NaN,"0,0,0,0,0,0,0,0,0,80,81,76,78,74,56,48,55,66,6...",NaN,NaN,NaN,NaN,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1...",NaN
2,2024-06-23 12:47:12,524.0,Test,"20,7,1,1,1,1,1,1,1,27,27,27,27,27,27,27,27,27,...","90,93,56,37,48,54,54,54,54,96,96,96,96,96,96,9...","53007,2408586,342804,289679,1324029,810164,131...","93603,181761,84172,65709,23167,77739,249791,37...","26687,59193,1407,5064,15911,29506,19154,55134,...","4455,19850,1391,2060,6806,25037,13219,47986,13...","1397,11155,1221,1622,3540,2779,7363,100311,149...",...,NaN,NaN,NaN,"0,0,0,0,0,0,0,0,0,65,70,83,88,90,91,94,96,98,0...",NaN,NaN,NaN,NaN,"1,2,3,4,5,6,6,7,8,9,10,11,12,14,15,16,17,18,19...",NaN
3,2024-06-23 12:17:12,594.0,Test,"94,93,100,83,74,66,64,77,80,83,74,61,57,48,54,...","60,53,61,40,56,40,34,53,53,75,80,67,81,66,57,6...","21107,34155,7968,161447,200475,15450,62679,148...","9971,23826,8971,89527,134669,32108,15140,18530...","1061,7828,2409,8608,24095,2332,5134,13160,3522...","81,7770,3904,4574,21301,2112,2129,22539,4538,1...","938,3348,8523,12855,20659,3195,18696,24935,900...",...,NaN,NaN,NaN,"0,0,0,0,0,0,0,0,0,62,56,49,45,47,54,56,55,57,5...",NaN,NaN,NaN,NaN,"1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,2...",NaN
4,2024-06-23 12:03:14,642.0,Test,"41,75,90,100,94,69,75,80,87,100,88,83,70,67,77...","26,26,26,21,40,44,40,29,14,16,13,13,16,16,26,2...","34584,57243,11051,14737,26732,1148507,1230442,...","21047,31510,47071,14349,25291,96983,159629,663...","2603,9222,6884,4684,24805,22357,6444,469,6815,...","1243,12640,9952,9798,19758,34829,28882,1572,12...","6382,27483,4788,9639,19198,6192,17864,1358,385...",...,NaN,NaN,NaN,"0,0,0,0,0,0,0,0,0,48,37,33,35,35,32,34,35,35,3...",NaN,NaN,NaN,NaN,"0,1,2,3,4,5,6,7,8,9,10,11,11,12,13,14,15,16,17...",NaN

# Processing Columns

In [4]:
# Removing NaN or Null values inside of dataset
def remove_nan(dataset):
    threshold = 0.5
    dataset_cleaned = dataset.loc[:, dataset.isnull().mean() < threshold]
    return dataset_cleaned

In [5]:
# Removing nan columns
dataset_cleaned = remove_nan(unprocs_data)

In [6]:
# Showing the result after removing columns
dataset_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/日期             83 non-null     object
 1   时长(Duration)/秒(ss)  82 non-null     float64
 2   Tag/备注              82 non-null     object
 3   Attention/注意力       82 non-null     object
 4   Relaxation/放松度      82 non-null     object
 5   Delta/δ波            82 non-null     object
 6   Theta/θ波            82 non-null     object
 7   Low-Alpha/低α波       82 non-null     object
 8   High-Alpha/高α波      82 non-null     object
 9   Low-Beta/低β波        82 non-null     object
 10  High-Beta/高β波       82 non-null     object
 11  Low-Gamma/低γ波       82 non-null     object
 12  Mid-Gamma/高γ波       82 non-null     object
 13  SyncRate/同步率        82 non-null     object
 14  Time-set/时间集合       82 non-null     object
dtypes: float64(1), object(14)
memory usage: 9.9+ KB

In [7]:
# Removing row that has nan as a value
dataset_cleaned = dataset_cleaned.dropna(axis=0)
dataset_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 0 to 81
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/日期             82 non-null     object
 1   时长(Duration)/秒(ss)  82 non-null     float64
 2   Tag/备注              82 non-null     object
 3   Attention/注意力       82 non-null     object
 4   Relaxation/放松度      82 non-null     object
 5   Delta/δ波            82 non-null     object
 6   Theta/θ波            82 non-null     object
 7   Low-Alpha/低α波       82 non-null     object
 8   High-Alpha/高α波      82 non-null     object
 9   Low-Beta/低β波        82 non-null     object
 10  High-Beta/高β波       82 non-null     object
 11  Low-Gamma/低γ波       82 non-null     object
 12  Mid-Gamma/高γ波       82 non-null     object
 13  SyncRate/同步率        82 non-null     object
 14  Time-set/时间集合       82 non-null     object
dtypes: float64(1), object(14)
memory usage: 10.2+ KB

In [8]:
# Change the columns head
cols = ['Date', 'Duration', 'Tag', 'Attention', 'Relaxation', 'Delta', 'Theta', 'Low-Alpha', 'High-Alpha', 'Low-Beta', 'High-Beta', 'Low-Gamma', 'Mid-Gamma', 'SyncRate', 'Time-set']

In [9]:
# Change the cols name
dataset_cleaned.columns = cols
dataset_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 0 to 81
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        82 non-null     object
 1   Duration    82 non-null     float64
 2   Tag         82 non-null     object
 3   Attention   82 non-null     object
 4   Relaxation  82 non-null     object
 5   Delta       82 non-null     object
 6   Theta       82 non-null     object
 7   Low-Alpha   82 non-null     object
 8   High-Alpha  82 non-null     object
 9   Low-Beta    82 non-null     object
 10  High-Beta   82 non-null     object
 11  Low-Gamma   82 non-null     object
 12  Mid-Gamma   82 non-null     object
 13  SyncRate    82 non-null     object
 14  Time-set    82 non-null     object
dtypes: float64(1), object(14)
memory usage: 10.2+ KB

In [10]:
dataset_cleaned.head()

,Date,Duration,Tag,Attention,Relaxation,Delta,Theta,Low-Alpha,High-Alpha,Low-Beta,High-Beta,Low-Gamma,Mid-Gamma,SyncRate,Time-set
0,2024-06-23 13:10:08,471.0,Test,"1,23,61,77,100,96,75,53,34,13,11,27,37,61,66,8...","1,4,10,26,53,44,43,26,20,30,38,53,48,54,48,60,...","686419,388430,78951,531079,43097,368312,39564,...","963980,77978,24009,217083,15199,173947,124644,...","40642,9504,11341,40053,18938,4297,11504,7229,1...","6310,15413,3183,10559,9190,20287,35483,10345,4...","42227,22239,4982,23503,15573,7181,27479,11368,...","76058,20485,15830,34049,26893,50096,24702,1675...","24805,26378,31172,29570,7398,14730,22928,12085...","10425,8994,5576,9507,7272,8062,20198,9095,1338...","0,0,0,0,0,0,0,0,0,83,74,61,58,52,52,59,71,78,8...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
1,2024-06-23 12:59:06,479.0,Test,"7,8,29,56,70,83,90,93,84,83,83,90,88,91,81,75,...","26,17,41,38,35,43,48,64,77,93,94,91,96,81,75,7...","1224512,101185,92870,203956,29915,548557,5351,...","143438,56625,157187,22542,26154,61326,7730,788...","50979,4404,31693,2212,7489,8689,3985,14981,786...","15409,3341,29821,3292,16163,14455,3828,6765,20...","10988,2659,15039,6505,21814,8239,2770,22010,72...","17866,7491,38808,5657,21317,29030,5748,8363,81...","6407,4646,44653,7357,20878,21921,1310,4060,112...","1883,1045,7720,1187,7577,4224,1371,2809,2370,1...","0,0,0,0,0,0,0,0,0,80,81,76,78,74,56,48,55,66,6...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
2,2024-06-23 12:47:12,524.0,Test,"20,7,1,1,1,1,1,1,1,27,27,27,27,27,27,27,27,27,...","90,93,56,37,48,54,54,54,54,96,96,96,96,96,96,9...","53007,2408586,342804,289679,1324029,810164,131...","93603,181761,84172,65709,23167,77739,249791,37...","26687,59193,1407,5064,15911,29506,19154,55134,...","4455,19850,1391,2060,6806,25037,13219,47986,13...","1397,11155,1221,1622,3540,2779,7363,100311,149...","768,3359,465,533,936,2984,6019,27219,210392,37...","484,1422,231,565,984,3218,4064,83643,47066,134...","201,1075,320,930,732,1988,3790,26083,25720,573...","0,0,0,0,0,0,0,0,0,65,70,83,88,90,91,94,96,98,0...","1,2,3,4,5,6,6,7,8,9,10,11,12,14,15,16,17,18,19..."
3,2024-06-23 12:17:12,594.0,Test,"94,93,100,83,74,66,64,77,80,83,74,61,57,48,54,...","60,53,61,40,56,40,34,53,53,75,80,67,81,66,57,6...","21107,34155,7968,161447,200475,15450,62679,148...","9971,23826,8971,89527,134669,32108,15140,18530...","1061,7828,2409,8608,24095,2332,5134,13160,3522...","81,7770,3904,4574,21301,2112,2129,22539,4538,1...","938,3348,8523,12855,20659,3195,18696,24935,900...","7666,9361,4651,10580,44420,3991,6205,17821,101...","2022,5246,4565,6083,9897,4840,3445,22542,3726,...","3479,2146,6594,3162,17536,1718,4091,9835,4026,...","0,0,0,0,0,0,0,0,0,62,56,49,45,47,54,56,55,57,5...","1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,2..."
4,2024-06-23 12:03:14,642.0,Test,"41,75,90,100,94,69,75,80,87,100,88,83,70,67,77...","26,26,26,21,40,44,40,29,14,16,13,13,16,16,26,2...","34584,57243,11051,14737,26732,1148507,1230442,...","21047,31510,47071,14349,25291,96983,159629,663...","2603,9222,6884,4684,24805,22357,6444,469,6815,...","1243,12640,9952,9798,19758,34829,28882,1572,12...","6382,27483,4788,9639,19198,6192,17864,1358,385...","5011,17427,9520,6921,6366,10772,40224,4518,141...","2152,5031,11224,23558,2234,6285,27132,1755,149...","374,3293,5083,2468,2814,1982,7248,653,5427,422...","0,0,0,0,0,0,0,0,0,48,37,33,35,35,32,34,35,35,3...","0,1,2,3,4,5,6,7,8,9,10,11,11,12,13,14,15,16,17..."

# Splitting the data

In [11]:
import os

# Define columns to explode
columns_to_explode = ['Attention', 'Relaxation', 'Delta', 'Theta', 'Low-Alpha', 'High-Alpha', 'Low-Beta', 'High-Beta', 'Low-Gamma', 'Mid-Gamma', 'SyncRate', 'Time-set']


# Prepare output directory
output_dir = 'row_files'
os.makedirs(output_dir, exist_ok=True)

# Function to explode specified columns and create a new DataFrame for each row
for index, row in dataset_cleaned.iterrows():
    # Create a new DataFrame for the current row's non-exploded data
    row_data = {'Date': [row['Date']], 'Duration': [row['Duration']], 'Tag': [row['Tag']]}
    row_df = pd.DataFrame(row_data)
    
    # Explode each specified column
    exploded_dfs = []
    max_length = 0
    for column in columns_to_explode:
        values = row[column].split(',')
        max_length = max(max_length, len(values))
        exploded_df = pd.DataFrame(values, columns=[column])
        exploded_dfs.append(exploded_df)
    
    # Extend the non-exploded data to match the length of the longest exploded column
    combined_df = pd.concat([row_df] * max_length).reset_index(drop=True)
    
    # Add exploded columns to the combined DataFrame
    for exploded_df in exploded_dfs:
        combined_df = pd.concat([combined_df.reset_index(drop=True), exploded_df.reset_index(drop=True)], axis=1)
    
    # Save to a CSV file for each row
    filename = os.path.join(output_dir, f'row_{index}.csv')
    combined_df.to_csv(filename, index=False)

print("All rows have been processed and saved as separate CSV files in the 'row_files' directory.")

All rows have been processed and saved as separate CSV files in the 'row_files' directory.